<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1>Сайт: <?= $page['name'] ?></h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="url">
                <tbody>
                <tr>
                    <td>ID</td>
                    <td><?= $page['id'] ?></td>
                </tr>
                <tr>
                    <td>Имя</td>
                    <td><?= $page['name'] ?></td>
                </tr>
                <tr>
                    <td>Дата создания</td>
                    <td><?= $page['created_at'] ?></td>
                </tr>
                </tbody>
            </table>
        </div>
        <h2 class="mt-5 mb-3">Проверки</h2>
        <form method="post" action="/urls/<?= $page['id'] ?>/checks">
            <input type="submit" class="btn btn-primary mb-3" value="Запустить проверку">
        </form>
        <table class="table table-bordered table-hover" data-test="checks">
            <tbody>
            <tr>
                <th>ID</th>
                <th>Код ответа</th>
                <th>h1</th>
                <th>title</th>
                <th>description</th>
                <th>Дата создания</th>
            </tr>
            <?php foreach ($checks as $check) : ?>
                <tr>
                    <td><?= $check['id'] ?? '' ?></td>
                    <td><?= $check['status_code'] ?? '' ?></td>
                    <td><?= $check['h1'] ?? '' ?></td>
                    <td><?= $check['title'] ?? '' ?></td>
                    <td><?= $check['description'] ?? '' ?></td>
                    <td><?= $check['created_at'] ?? '' ?></td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    </div>
</main>